#include "mcworld/terrain.hpp"
#include "terrain_internal.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string_view>

namespace {
int failures = 0;
void check(bool condition, std::string_view message) {
    if (!condition) {
        std::cerr << "FAIL: " << message << '\n';
        ++failures;
    }
}

class FixedBiome final : public mcworld::BiomeSource {
public:
    explicit FixedBiome(mcworld::Biome biome) : biome_(biome) {}
    mcworld::Biome sample(const mcworld::OverworldNoiseRouter&, int, int, int) const override { return biome_; }
private:
    mcworld::Biome biome_;
};

void testClimate() {
    using enum mcworld::Biome;
    mcworld::RouterSample c;
    c.continentalness = -1.1F;
    check(mcworld::resolveOverworldBiome(c) == MushroomFields, "mushroom continentalness");
    c.continentalness = -.6F;
    c.temperature = -.8F;
    check(mcworld::resolveOverworldBiome(c) == DeepFrozenOcean, "cold deep ocean");
    c.temperature = -.45F;
    check(mcworld::resolveOverworldBiome(c) == DeepFrozenOcean, "shared interval boundary uses first registered point");
    c.temperature = -.4499F;
    check(mcworld::resolveOverworldBiome(c) == DeepColdOcean, "quantized temperature crosses interval boundary");
    c.continentalness = -.3F;
    c.temperature = .8F;
    check(mcworld::resolveOverworldBiome(c) == WarmOcean, "warm ocean");
    c.continentalness = .1F;
    c.erosion = .3F;
    c.ridges = -.3F;
    check(mcworld::resolveOverworldBiome(c) == Desert, "hot inland surface");
    c.temperature = 0;
    c.vegetation = .85F;
    c.depth = .5F;
    check(mcworld::resolveOverworldBiome(c) == LushCaves, "humid underground climate");
    c.vegetation = 0;
    c.erosion = -.8F;
    c.depth = 1.1F;
    check(mcworld::resolveOverworldBiome(c) == DeepDark, "deep dark climate");
    c.depth = .5F;
    c.erosion = .8F;
    c.ridges = -.95F;
    check(mcworld::resolveOverworldBiome(c) == SulfurCaves, "26.3 sulfur cave climate");
    c.temperature = std::numeric_limits<float>::quiet_NaN();
    bool rejected = false;
    try { (void)mcworld::resolveOverworldBiome(c); } catch (const std::invalid_argument&) { rejected = true; }
    check(rejected, "non-finite climate rejected");
    mcworld::OverworldNoiseRouter router(12345);
    check(mcworld::sampleOverworldBiome(router, -1, -1, -1) ==
          mcworld::resolveOverworldBiome(router.sample(-4, -4, -4)), "negative coordinates floor to quart lattice");
}

void testJavaBiomeSlices() {
    // Java OverworldBiomeBuilder: 7,594 registered points, queried with brute-force
    // first-registered tie-breaking (the project's documented lookup policy).
    // FNV-1a over Biome ordinals for all 9,100 interior surface climate slices.
    constexpr float ts[]{-.7F,-.3F,0,.4F,.8F}, hs[]{-.7F,-.2F,0,.2F,.7F};
    constexpr float cs[]{-.15F,0,.15F,.65F}, es[]{-.9F,-.6F,-.3F,0,.3F,.5F,.8F};
    constexpr float ws[]{-.97F,-.85F,-.65F,-.5F,-.33F,-.15F,0,.15F,.33F,.5F,.65F,.85F,.97F};
    std::uint64_t hash=0xcbf29ce484222325ULL;
    for(float t:ts) for(float h:hs) for(float c:cs) for(float e:es) for(float w:ws) {
        mcworld::RouterSample sample{};
        sample.temperature=t;sample.vegetation=h;sample.continentalness=c;
        sample.erosion=e;sample.ridges=w;
        hash^=static_cast<std::uint8_t>(mcworld::resolveOverworldBiome(sample));
        hash*=0x100000001b3ULL;
    }
    check(hash==0x869f8e9f6b6f28d6ULL, "Overworld biome slices match Java registration table");
}

void testJavaCarvingMasks() {
    // Generated by executing the 26.3 WorldCarver/CaveWorldCarver/CanyonWorldCarver
    // geometry in Java with vanilla providers, java.util.Random, and Mth's table.
    // Hashes cover every mask bit in z/x/y order, independently of our density noise.
    struct Fixture {std::int64_t seed;int x,z,count;std::uint64_t hash;};
    constexpr Fixture fixtures[]{
        {0,0,0,86,0xc45da01c1bf106e7ULL},
        {12345,-1,0,1907,0xb95bfcdfeb2eda62ULL},
        {91,20,-12,4803,0x939e94165c7db5fcULL},
        {-1,100,100,1902,0x6937227dbd2bdbdfULL},
        {987654321,-45,50,208,0x517021480cfcdfe9ULL}
    };
    for(auto f:fixtures) {
        auto mask=mcworld::detail::buildCarvingMask(f.x,f.z,f.seed);
        std::uint64_t hash=0xcbf29ce484222325ULL;int count=0;
        for(bool bit:mask) {hash^=bit;hash*=0x100000001b3ULL;count+=bit;}
        check(count==f.count && hash==f.hash,"full carving mask matches Java reference");
        for(int z=0;z<16;++z) for(int x=0;x<16;++x) {
            check(!mask[(z*16+x)*384+1],"carvers preserve Y=-63");
            for(int y=313;y<320;++y) check(!mask[(z*16+x)*384+y+64],"carvers protect top seven blocks");
        }
    }
}

void testCarvingRuns() {
    using namespace mcworld;
    using enum Block;
    TerrainChunk chunk;
    detail::CarvingMask mask(16*16*384);
    for(auto p:std::array<BlockPosition,3>{{{0,70,0},{0,80,0},{0,80,1}}}) {
        chunk.set(p.x,p.y,p.z,Grass);chunk.set(p.x,p.y-1,p.z,Dirt);
        mask[(p.z*16+p.x)*384+p.y+64]=true;
    }
    chunk.primeHeightmaps();
    OverworldNoiseRouter router(0);detail::Aquifer aquifer(router,false);
    std::vector<BlockPosition> repaired;std::vector<int> heights;
    detail::applyCarvingMask(chunk,mask,aquifer,[&](int x,int y,int z,bool fluid) {
        repaired.push_back({x,y,z});heights.push_back(chunk.worldSurface[z*16+x]);
        check(!fluid,"above-sea-level carving exposes soil to air");
        return std::optional{Grass};
    });
    check(repaired==std::vector<BlockPosition>{{0,69,0},{0,79,0},{0,79,1}},
          "carving visits bottom-to-top runs within X/Z columns");
    check(heights==std::vector<int>{81,80,80},"topMaterial sees live post-carve heights");
    check(chunk.at(0,69,0)==Grass && chunk.at(0,79,0)==Grass,"each carving run repairs exposed soil");
}

void testBiomeEnvironment() {
    using namespace mcworld;
    // SHA-256/zoom vectors from Java MessageDigest and BiomeManager's methods.
    struct Fixture {std::int64_t seed;std::uint64_t zoom,hash;};
    constexpr Fixture fixtures[]{
        {0,0x7a0b81a1f57055afULL,0x13b3c3a10141fdb0ULL},
        {1,0xa63f41d436a19f7cULL,0x548e7e9fd4003defULL},
        {-1,0x5dce615644aea312ULL,0xabf4a6150c3526e3ULL},
        {12345,0x04139124513554e1ULL,0x7dbc941f8e09adfdULL},
        {std::numeric_limits<std::int64_t>::min(),0x58763b3a9a6cade6ULL,0x5f66dd4bb8e7b526ULL},
        {std::numeric_limits<std::int64_t>::max(),0x63a17374cca6696aULL,0xa68aa20a3e4f9897ULL}
    };
    for(auto f:fixtures) {
        auto seed=detail::biomeZoomSeed(f.seed);
        check(seed==f.zoom,"biome zoom seed matches Java SHA-256 byte order");
        std::uint64_t hash=0xcbf29ce484222325ULL;
        for(int x=-19;x<=19;++x) for(int y=-67;y<=323;y+=13) for(int z=-19;z<=19;z+=3) {
            auto q=detail::zoomedBiomeQuart(seed,x,y,z);
            for(int coordinate:{q.x,q.y,q.z}) {hash^=static_cast<std::uint32_t>(coordinate);hash*=0x100000001b3ULL;}
        }
        check(hash==f.hash,"jittered quart selection matches Java including negative and edge positions");
    }
    class EdgeBiome final : public BiomeSource {
    public:
        Biome sample(const OverworldNoiseRouter&,int x,int,int) const override {return x<0?Biome::Desert:Biome::Plains;}
    } source;
    TerrainChunk chunk;chunk.biomes.fill(Biome::Plains);
    OverworldNoiseRouter router(12345);
    auto biomes=detail::makeBlockBiomeGetter(chunk,router,source,true);
    bool neighbor=false,center=false;
    for(int y=80;y<120;++y) {
        auto b=biomes(0,y,8);
        neighbor|=b==Biome::Desert;center|=b==Biome::Plains;
    }
    check(neighbor && center,"material biome zoom uses neighboring palettes across chunk boundaries");

    // Fixed-seed Java SimplexNoise/NoiseStack and Biome.TemperatureModifier.FROZEN.
    std::uint64_t hash=0xcbf29ce484222325ULL;int count=0;
    for(int x=-1000;x<=1000;x+=7) for(int z=-1000;z<=1000;z+=11) {
        bool melt=detail::meltsFrozenOceanIceberg(Biome::FrozenOcean,x,z);
        hash^=melt;hash*=0x100000001b3ULL;count+=melt;
    }
    check(count==28044 && hash==0x94bc94feca491c25ULL,"iceberg temperature adjustment matches Java");
    check(detail::meltsFrozenOceanIceberg(Biome::DeepFrozenOcean,0,0),"deep frozen ocean always exceeds melting threshold");
}

void testRandomAndAquifer() {
    mcworld::detail::LegacyRandom random(0);
    check(random.nextInt(1000) == 360 && random.nextInt(1000) == 948, "Java bounded random vector");
    mcworld::detail::LegacyRandom longs(0);
    check(longs.nextLong() == static_cast<std::uint64_t>(-4962768465676381896LL), "Java signed nextLong vector");
    check(mcworld::detail::floorDiv(-1, 16) == -1 && mcworld::detail::floorDiv(-16, 16) == -1,
          "negative aquifer grid division");
    mcworld::OverworldNoiseRouter router(12345);
    mcworld::detail::Aquifer disabled(router, false), first(router, true), second(router, true);
    using enum mcworld::Block;
    check(disabled.sample(0, 62, 0, 0).block == Water, "global water below sea level");
    check(disabled.sample(0, 63, 0, 0).block == Air, "sea level is exclusive");
    check(disabled.sample(0, -55, 0, 0).block == Lava, "global lava below -54");
    check(disabled.sample(0, -54, 0, 0).block == Water, "global lava cutoff is exclusive");
    check(first.sample(0, -60, 0, 1).block == Stone, "positive density beats global lava");
    check(first.sample(0, -55, 0, -1).block == Lava, "enabled aquifer retains global lava");
    struct Probe { int x, y, z; mcworld::detail::Substance substance; };
    std::vector<Probe> probes;
    for (int x = -17; x <= 17; x += 2) for (int y = -53; y <= 65; y += 11)
        probes.push_back({x, y, -x, first.sample(x, y, -x, 0)});
    bool pressureBarrier = false;
    for (auto it = probes.rbegin(); it != probes.rend(); ++it) {
        auto result = second.sample(it->x, it->y, it->z, 0);
        check(result.block == it->substance.block && result.schedule == it->substance.schedule,
              "aquifer decisions independent of cache fill order");
        pressureBarrier |= result.block == Stone;
    }
    check(pressureBarrier, "aquifer pressure can retain solid at zero density");
}

void testChunks() {
    using enum mcworld::Block;
    mcworld::TerrainChunk empty;
    empty.primeHeightmaps();
    check(empty.worldSurface[0] == -64 && empty.oceanFloor[0] == -64, "empty heightmap sentinel");
    empty.set(0, 5, 0, Stone);
    empty.set(0, 8, 0, Water);
    empty.primeHeightmaps();
    check(empty.worldSurface[0] == 9 && empty.oceanFloor[0] == 6, "fluid and floor heightmaps differ");
    empty.set(0, 12, 0, PowderSnow);
    empty.primeHeightmaps();
    check(empty.worldSurface[0]==13 && empty.oceanFloor[0]==6 && empty.motionBlocking[0]==9 &&
          empty.motionBlockingNoLeaves[0]==9,"powder snow excluded from motion and ocean-floor heightmaps");
    bool rejected = false;
    try { empty.set(-1, 0, 0, Stone); } catch (const std::out_of_range&) { rejected = true; }
    check(rejected, "chunk-local access checked");

    mcworld::OverworldNoiseRouter router(12345), independent(12345);
    mcworld::OverworldTerrainGenerator generator(router), other(independent);
    auto a = generator.generate(-1, 0);
    (void)generator.generate(0, 0);
    auto again = generator.generate(-1, 0);
    auto b = other.generate(-1, 0);
    check(a.blocks == b.blocks && a.blocks == again.blocks, "chunk blocks independent of generation order");
    check(a.biomes == b.biomes && a.biomes == again.biomes, "biome palettes deterministic");
    check(a.fluidPostProcessing == b.fluidPostProcessing && a.fluidPostProcessing == again.fluidPostProcessing,
          "fluid update positions deterministic");
    std::size_t deepslate = 0, fluids = 0;
    for (int z = 0; z < 16; ++z) for (int x = 0; x < 16; ++x) {
        check(a.at(x, -64, z) == Bedrock, "bedrock floor survives carving");
        int surface = -64, floor = -64;
        for (int y = -64; y < 320; ++y) {
            auto block = a.at(x, y, z);
            if (block != Air) surface = y + 1;
            if (mcworld::blocksMotion(block)) floor = y + 1;
            deepslate += block == Deepslate;
            fluids += mcworld::isFluid(block);
        }
        check(a.worldSurface[z * 16 + x] == surface && a.oceanFloor[z * 16 + x] == floor,
              "heightmaps describe post-carver blocks");
    }
    check(deepslate > 0 && fluids > 0, "terrain contains underground materials and fluids");
    for (auto p : a.fluidPostProcessing) check(mcworld::isFluid(a.at(p.x, p.y, p.z)), "only existing fluids queued");
    rejected = false;
    try { (void)generator.generate(std::numeric_limits<int>::max(), 0); }
    catch (const std::invalid_argument&) { rejected = true; }
    check(rejected, "overflowing chunk coordinate rejected");

    mcworld::TerrainOptions options;
    options.carvers = false;
    auto before = mcworld::OverworldTerrainGenerator(router, options).generate(-1, 0);
    check(before.blocks != a.blocks, "carver mask changes terrain");
    for (std::size_t i = 0; i < a.blocks.size(); ++i) {
        if (a.blocks[i] != before.blocks[i]) {
            check(!mcworld::isSolid(a.blocks[i]) || a.blocks[i] == Grass || a.blocks[i] == Mycelium || a.blocks[i] == Dirt,
                  "carvers remove terrain or repair exposed dirt");
        }
    }
}

void testMaterials() {
    using enum mcworld::Block;
    mcworld::OverworldNoiseRouter router(91);
    auto slab = [](mcworld::Biome biome) {
        mcworld::TerrainChunk c;
        c.biomes.fill(biome);
        for (int z = 0; z < 16; ++z) for (int x = 0; x < 16; ++x)
            for (int y = -64; y <= 180; ++y) c.set(x, y, z,Stone);
        c.primeHeightmaps();
        return c;
    };
    auto desert = slab(mcworld::Biome::Desert);
    mcworld::detail::buildMaterials(desert, router, false);
    check(desert.at(8, 180, 8) == Sand, "desert surface is sand");
    check(std::count(desert.blocks.begin(), desert.blocks.end(), Sandstone) > 0, "sandstone below desert sand");
    auto plains = slab(mcworld::Biome::Plains);
    mcworld::detail::buildMaterials(plains, router, false);
    check(plains.at(8, 180, 8) == Grass && plains.at(8, 179, 8) == Dirt, "plains topsoil sequence");
    check(plains.at(8, -64, 8) == Bedrock && plains.at(8, -20, 8) == Deepslate, "bedrock and underground priority");
    for(int direction=0;direction<4;++direction) {
        mcworld::TerrainChunk slope;
        slope.biomes.fill(mcworld::Biome::JaggedPeaks);
        for(int x=0;x<16;++x) for(int z=0;z<16;++z) {
            int height=180+(direction<2?x:z)*(direction%2==0?2:-2);
            for(int y=170-32;y<=height;++y) slope.set(x,y,z,Stone);
        }
        slope.primeHeightmaps();
        int top=slope.worldSurface[8*16+8]-1;
        mcworld::detail::buildMaterials(slope,router,false);
        check(slope.at(8,top,8)==(direction==1 || direction==2?Stone:Snow),
              "SteepCondition uses negative X or positive Z gradient only");
    }
    auto sulfur = slab(mcworld::Biome::SulfurCaves);
    mcworld::detail::buildMaterials(sulfur, router, false);
    check(std::count(sulfur.blocks.begin(), sulfur.blocks.end(), Sulfur) > 0 &&
          std::count(sulfur.blocks.begin(), sulfur.blocks.end(), Cinnabar) > 0, "sulfur cave bands");
    std::size_t oreCount = 0;
    for (auto coordinate : std::array<std::array<int, 2>, 4>{{{0, 0}, {20, -12}, {100, 100}, {-45, 50}}}) {
        auto veins = slab(mcworld::Biome::Plains);
        veins.chunkX = coordinate[0];
        veins.chunkZ = coordinate[1];
        mcworld::detail::buildMaterials(veins, router, true);
        for (int z = 0; z < 16; ++z) for (int x = 0; x < 16; ++x) for (int y = -64; y < 320; ++y) {
            auto b = veins.at(x, y, z);
            if (b == CopperOre || b == RawCopper) {
                check(y >= 0 && y < 50, "copper veins respect height range");
                ++oreCount;
            }
            if (b == DeepslateIronOre || b == RawIron) {
                check(y >= -60 && y < -8, "iron veins respect height range");
                ++oreCount;
            }
        }
        check(veins.at(0, -64, 0) == Bedrock, "bedrock has priority over veins");
    }
    check(oreCount > 0, "ore-vein material rules produce ore");
    mcworld::TerrainOptions options;
    options.biomes = std::make_shared<FixedBiome>(mcworld::Biome::Desert);
    options.carvers = false;
    auto fixed = mcworld::OverworldTerrainGenerator(router, options).generate(0, 0);
    check(std::all_of(fixed.biomes.begin(), fixed.biomes.end(), [](auto b) { return b == mcworld::Biome::Desert; }),
          "injected biome provider fills palette");
}
}

int main() {
    testClimate();
    testJavaBiomeSlices();
    testJavaCarvingMasks();
    testCarvingRuns();
    testBiomeEnvironment();
    testRandomAndAquifer();
    testChunks();
    testMaterials();
    if (failures) std::cerr << failures << " terrain checks failed\n";
    else std::cout << "All terrain checks passed\n";
    return failures ? 1 : 0;
}
